repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8"]
        #args: ["--max-line-length=88", "--per-file-ignores=tests/*:F841", "--extend-ignore=E203,E501"]
